<!doctype html>
<?php 
  /* HEAD */
  $lang       = 'en';
  $head_title = 'Essay — A Huge, Ever-Growing, Pulsating Brain that Rules from the Empty Center of a City Called Tokyo — Art Space Tokyo';
  $head_desc  = 'An essay by Roger McDonald';
  $fburl      = 'read.artspacetokyo.com/essays/pulsating-tokyo/';
  $fbimg      = '';
  
  /* MENU */
  $current_page = 'pulsating-tokyo';
?>
<?php include($_SERVER['DOCUMENT_ROOT'] . '/templates/head.php'); ?>

  <body class="essay">
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/templates/header.php'); ?>

    <div class="container content">
      
      <div class="row">
        <div class="twelvecol">
          <div class="content_head">
            <h1>A Huge, Ever-Growing, Pulsating<br /> Brain that Rules from the Empty<br />Center of a City Called Tokyo</h1>
            <h2 class="subtitle"><em>by</em> Roger McDonald</h2>
          </div>          
        </div>
      </div>
      
      <div class="row">
        <div class="eightcol">
          <!-ESSAY BODY -->
          <div class="essay_body">
            <p>My memories of being brought up in Tokyo in the 1970s are faint, but very often brought back to life by small encounters I have in the city. One of my overwhelming memories is that everything was colored in a shade of brown or beige. This no doubt reflects a very particular 1970s aesthetic of American-influenced expatriate culture in Tokyo — the Tokyo American Club, my kindergarten, carpets at home and so on. Although I am from a mixed British-Japanese family background, the Tokyo of my childhood is heavily colored by a veneer of American home furnishings, architectures and television programs.</p>
            <p>And yet amidst these memories are splendid spaces like the lobby of the old wing of the Hotel Okura. To this day largely unchanged, here one encounters the Tokyo of Sean Connery’s James Bond in 1967’s <em>You Only Live Twice</em>, with its elegant mixing of Japanese traditional and International Modern styles. Built in 1962 by architect Yoshiro Taniguchi, the Hotel Okura’s interior remains one of the most stunning spaces in Tokyo, for me an architectural symbol of my own bicultural background.</p>
            <p>Rather less grand, but equally wondrous is the wax museum in Tokyo Tower. A masterpiece of awkward, vernacular design, this museum is one of my favorites in Tokyo. Although a second, much taller and more spectacular New Tokyo Tower is due to open in Oshiage in 2011,<sup id="ref1"><a href="#fn1">1</a></sup> the original 1958 tower retains much of its early 1960s charm. I remember visiting the wax museum as a child and standing wide-eyed before dusty figures of politicians or the somehow very odd-looking <em>Last Supper of Christ</em>. Only later did I come to appreciate the museum’s collection of <em>Krautrock</em> musicians, standing in their flared trousers and long kaftan coats, surrounded by an impressive collection of memorabilia from this genre. Tokyo makes it possible for a myriad of personal interests or minor cultures to manifest themselves in this way, a consequence of the city’s seemingly endless appetite for curiosities.</p>
            <p>Although Tokyo seems to change constantly, it is a city that manages to remain embedded in the memory of its inhabitants and visitors, not so much through its physical presence as through its ongoing metamorphosis. One often hears people comment on what used to stand somewhere, mapping out an effective geography of traces and memories. There does not seem to be such importance placed on notions of maintaining something in its proper place for eternity. Rather, places are reinvented in multiple configurations, which can change with the passage of time and the fluctuations of one’s subjectivity and memory. Maybe this is why so much significance is placed every holiday period on people going back to their <em>furusato</em> or hometown, away from Tokyo and back to somewhere with roots.</p>
            <p>Tokyo is also remembered and its histories told particularly powerfully through the medium of photography, and more recently, film and video. This is an interesting fact to consider for a city that was almost totally annihilated twice during the 20th century — first through a major earthquake in 1923 and then through firebombing in 1945. One can argue that the city has undergone countless other, more tempered phases of annihilation in the postwar period as developers and city councils continuously redesign neighborhoods, tearing down buildings and parks in cycles of little more than twenty to thirty years. The role of photographers in such an absorbed city has therefore been significant. From the work of early figures such as Ihei Kimura to 1960s mavericks like Daido Moriyama and Nobuyoshi Araki to that of more recent practitioners such as Naoya Hatakeyama and Rinko Kawauchi, Tokyo is a city that has been caught and archived by the camera’s lens. Can we suggest that it has been photographs that have offered Tokyo a sense of place and of history, by providing it with a memory of reproduction?</p>
            <p>This sense of physical impermanence makes Tokyo something like a huge, ever-evolving John Cage composition, whirling itself through chance procedures and the interventions of its inhabitants/users. Few anchor points exist to bind histories to places or people to places, except perhaps for the vast emptiness of the Imperial Palace grounds in the center of the city. As Roland Barthes famously wrote in his analysis of Japan <em>Empire of Signs</em> (1970), Tokyo is a city with an “empty center,” in contrast to Western cities, which place most of their important civic functions and architectures in a fully meaningful, significant core. The palace remains a place of symbolism where an essentially ‘empty’ Emperor resides and performs complex rituals on behalf of the nation. One of the consequences of this ‘emptiness’ has been the lack of a popular sense of political engagement that continues today. With the exception of the student demonstrations of the 1960s and the terrorist activities of the Japanese Red Army in the 1970s, Tokyo has seen very little popular protest or civil disturbance, at least in the European mold. The emergence of <em>manga kissa</em> cafés<sup id="ref2"><a href="#fn2">2</a></sup> and the subsequent phenomenon of ‘Net café refugees’<sup id="ref3"><a href="#fn3">3</a></sup> points toward the greater privatization of public spaces. These ‘empty’ spaces can easily be ‘filled’ for a few hours by various kinds of people who either sleep in them or plug into the Internet or other forms of mass entertainment. Not too unlike the Emperor’s secret rituals, we do not see what kinds of silent ceremonials go on in the tiny booths of such cafés.</p>
            <p>In discussing Tokyo’s art spaces, it becomes necessary first to recognize the city’s temporal nature and the ways in which it has passed its stories and histories on through various technologies and rituals. The histories of art in Tokyo have also reflected this condition to varying degrees. I must briefly mention the Japan Folk Crafts Museum (Nippon Mingeikan), which opened its doors as a museum early on in 1936. The Mingeikan is still a unique Tokyo museum, starting with its request that visitors remove their shoes and wear slippers upon entering. From the perspective of art spaces as physical architectures, Tokyo presents a relatively new arena. However, as I suggest, if we consider Tokyo to be a city that also constructs its own unique methods and spaces for telling stories, a different history of art spaces emerges.</p>
            <p>This story is also a partly invisible story, or perhaps it would be better to say that it is a story about almost invisible spaces. Certainly in the postwar period, a number of avant-garde art events and actions have taken place in and around Tokyo—the more well known being held on trains, the tops of buildings and on the streets. However, it is only from the 1990s that Tokyo has experienced what can be called a history of ‘alternative spaces’ along the lines of European or American models.</p>
            <p>This evolution of Tokyo’s alternative spaces has its origins in the artist-run initiatives and squats of the early 1970s of New York and major European cities. In 1970 the American artist Robert Smithson was building his monumental land artwork <em>Spiral Jetty</em>, espousing a critical position against urban art institutions; the very same year saw Japan engulfed in the opening of Expo ’7o in Osaka and the unveiling of Taro Okamoto’s giant quasi-primitive <em>Tower of the Sun</em> monument. In many ways the 1970s in Europe and the United States was a period of increasing movement away from institutional art spaces into derelict industrial spaces and lofts. In Japan, Expo ’70 symbolized a moment of victory for visionary young architects who realized their structures with huge influxes of public money. However, Japan’s arts policy settled firmly into the so called <em>hakomono gyosei</em>, or box-building policy, which encouraged construction of boxy museums. The policy continues almost unabated to this day on various scales.</p>
            <p>In Tokyo the now non-existent Sagacho Exhibit Space, located in an old food warehouse, is considered to be one of the city’s first alternative art spaces, opening in the early 1980s. Closed in 2002, its building was torn down to make way for new developments in 2003. Since its closure, there has been no comparable alternative space in Tokyo, bar only a stream of smaller, tactical initiatives, some of which survived for several years only to fade out due to lack of funds.</p>
            <p>The reasons for this lack of survival among Tokyo’s alternative art spaces are no doubt tied closely to the nature of the city and its economics. Real-estate and rental prices remain high, and vacant buildings are usually tightly sealed to prevent squatting or quickly refurbished to await new occupants. Added to this is the frankly very poor infrastructural and financial support—either from the state or the city—for contemporary art in Tokyo. Funding is difficult to find and certainly not available for rental or running costs. This has created a ‘realpolitik’ in which artists and curators must operate. New project spaces or initiatives must invariably plan ahead and devise viable business models if they are to sustain themselves for more than a brief period. In this sense, art spaces may have to look like any other small business operating in Tokyo—and become just as invisible. Art finds itself sandwiched between different categories or functions and must find its place in the relative disorder of the city fabric. Unlike their New York or London East End counterparts, Tokyo’s art spaces have rarely been able to advertise themselves loudly. Rather, like chameleons, they tend to remain hidden or coexist symbiotically next to neighboring businesses and homes.</p>
            <p>However, Tokyo supports one of the most advanced public transportation systems in the world. The lack of easily identifiable cultural or civic centers is counterbalanced by the considerable mobility of its inhabitants, who can safely and swiftly journey through the city, linking various small spaces as they wish. Like Michel de Certeau’s analysis of the city walker who carves out unique pathways through the formally controlled environment, Tokyo’s infrastructure encourages individuals to traverse spaces and ‘draw’ their own maps, molding a very specific understanding of the city’s art spaces that does not privilege spaces so much as the creation of certain passages and durations. The density of the city perhaps shifts the focus from the spaces themselves to the operations that link them together, forming crisscrossed paths through Tokyo. Furthermore it is interesting to think of the numerous businesses in Tokyo that trade in time, including various service hotels, Internet cafés, massage parlors and karaoke booths. These establishments charge customers by the hour for the use of usually compact rooms or cubicles. Related to this would be the unique system of so-called ‘rental galleries’ in Japan — spaces that charge artists for the use of their exhibition space, normally for one week. The artist Hiroharu Mori created a text work for an Arts Initiative Tokyo project in 2007 which humorously contrasts rental galleries with karaoke booths in the Ginza area of Tokyo. The work consists of the following paragraph:</p>
            <blockquote><p>According to my research on the Internet, there are over sixty rental galleries situated in prime locations throughout Tokyo’s famous Ginza district. A breakdown of these galleries reveals that fifty-two indicate rental fees on the Internet. The average cost of these rental spaces is ¥267,807 per week (open six days a week). The average opening hours of these galleries per day is seven and a half hours. Therefore we can surmise that an average gallery space is available for ¥5,844 per hour. On the other hand, there are ten major karaoke boxes in the Ginza area as well. The average rental price for these places is ¥695 per hour.</p>
            <p>By the way, if I could sing a song for six days straight at a karaoke box, it would cost me ¥31,278. But how many songs do I need to sing before I become an established artist?<sup id="ref4"><a href="#fn4">4</a></sup></p></blockquote>
            <p>Although rental galleries still make up a sizeable part of Tokyo’s art spaces, since the late 1990s their scale and significance has somewhat decreased. This is due to the changing expectations of young art students as well as to the emergence of newer commercial gallery spaces, many of which combine multiple different functions including gallery spaces, shops and bar spaces.</p>
            <p>Being spaceless is today both a result of Tokyo’s exacting realestate market as well as of its very specific social and psychological geographies. I would suggest that it is in fact the most effective method for operating in Tokyo at a time when the demands for space are greater than ever. In suggesting this, I am keenly aware of many key historical precedents that have also respected the route of least spatial conquest in engaging with art. Marcel Duchamp’s <em>Boite en Valise</em> and its questioning of the relevance of authenticity in museums; André Malraux’s proposal for a ‘Museum without Walls’ where the power of photography and reproduction techniques could render art spaces less important; the many ingenious and humorous multiples of Fluxus artists; and a panoply of more recent manifestations and experiments including Yutaka Matsuzawa’s radical proposition to ‘vanish objects’ in the 1960s and Tsuyoshi Ozawa’s ‘Nasubi Gallery’ made in tiny milk delivery crates in 1992. Matsuzawa, who died in 2007, is one of the most interesting artists in this regard, often considered to be a father of conceptual art in Japan. During the 1965 Yomiuri Independent Exhibition, he distributed fliers to the gathered visitors with the instruction to close their eyes and imagine themselves in a far away place, which he called his <em>‘Han Bunmei Ten’</em> (Anti-Civilization Exhibition). Inspired by Buddhist metaphysics, mysticism and telepathy, Matsuzawa’s immaterial gesture embodies the most radical break with the sanctioned art space in Japan.</p>
            <p>Standing amidst the whirlwind of a busy Tokyo crossing with one’s nervous system assaulted on all fronts, Matsuzawa’s almost invisible gesture of closing the eyes makes a certain kind of sense. It suggests that the holy grail of the white cube space may not be so final here and that slight gestures or the simple act of imagining can momentarily open up quite unexpected spaces for art and for a different kind of consciousness, pulsating with other kinds of codes and rules from what the city nurtures so confidently.</p>
            
            <div class="footnotes">
              <h4>Noted</h4>
            	<ol>
            		<li id="fn1">Under construction to accommodate broadcasting requirements when Japanese television turns digital in 2011, the 2,080-foot-tall New Tokyo Tower (officially named Tokyo Sky Tree in June 2008) will be the tallest structure in Japan.<a href="#ref1">↩</a></li>
            		<li id="fn2">These twenty-four hour cafés offer an array of manga for customers to browse.<a href="#ref2">↩</a></li>
            		<li id="fn3">Young people who are opting to make use of the cheap food, drink and wash facilities in these cafés rather than rent their own apartments.<a href="#ref3">↩</a></li>
            		<li id="fn4">From <em>How Many Songs?</em>, included in the journal <em>Museum is Over! If you want it</em>, published by <span class="sc">AIT</span> in March 2007 on the occasion of <em>16 Hour Museum</em> in Tokyo.<a href="#ref4">↩</a></li>
            	</ol>
            	<h4 style="margin-top: 30px;">About the Title</h4>
            	<p>The title for this essay comes from the Orb’s 1989 song <em>A Huge Ever Growing Pulsating Brain That Rules from the Centre of the Ultraworld</em> (Big Life, <span class="sc">WAU</span>/Mr. Modo Records).</p>
            </div>
          
          
            <!-AUTHOR / INTERVIEW BIOS -->
            <div class="bio bottom">
              
              <!-BIO IMAGE ON RIGHT -->
              <div>
                <div class="eightcol" style="margin-top: 30px;">
                  <h4>About the Author</h4>
                  <p>Born in Tokyo in 1971, Roger McDonald was educated in the UK. After completing his doctorate in art history, he returned to Japan to work as assistant curator on the first Yokohama Triennale in 2001. He is one of the founding members and deputy director of the nonprofit curatorial collective, <a href="http://www.a-i-t.net" class="out">Arts Initiative Tokyo</a> (<span class="sc">AIT</span>). He has curated a number of exhibitions including the <span class="sc">AIT</span>’s <em>Hour Museums</em> and The Singapore Biennale in 2006. In 2012 he opened <a href="http://www.fenbergerhouse.com/" class="out">The Fenberger House Museum</a>, a small private house museum in the mountains of Nagano prefecture. He lectures at Joshi and Tokyo Zokei art universities.</p>
                </div>
                <div class="fourcol last">
                  <img src="/images/people/roger.png" alt="Roger McDonald" />
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div class="threecol submenu last">
          <?php include($_SERVER['DOCUMENT_ROOT'] . '/templates/submenu-essays.php'); ?>
          <?php include($_SERVER['DOCUMENT_ROOT'] . '/templates/purchase.php'); ?>
        </div>
      </div>
    </div>
    
    <?php include($_SERVER['DOCUMENT_ROOT'] . '/templates/footer.php'); ?>
  </body>
</html>